// Base de datos completa de países para numismática
const COUNTRIES = {
    'AB': { name: 'Abjasia', flag: '🏴', continent: 'Asia' },
    'AF': { name: 'Afganistán', flag: '🇦🇫', continent: 'Asia' },
    'AL': { name: 'Albania', flag: '🇦🇱', continent: 'Europa' },
    'DE': { name: 'Alemania', flag: '🇩🇪', continent: 'Europa' },
    'DDR': { name: 'Alemania República Democrática', flag: '🏴', continent: 'Europa (Histórico)' },
    'AD': { name: 'Andorra', flag: '🇦🇩', continent: 'Europa' },
    'AO': { name: 'Angola', flag: '🇦🇴', continent: 'África' },
    'AG': { name: 'Antigua y Barbuda', flag: '🇦🇬', continent: 'América del Norte' },
    'SA': { name: 'Arabia Saudí', flag: '🇸🇦', continent: 'Asia' },
    'DZ': { name: 'Argelia', flag: '🇩🇿', continent: 'África' },
    'AR': { name: 'Argentina', flag: '🇦🇷', continent: 'América del Sur' },
    'AM': { name: 'Armenia', flag: '🇦🇲', continent: 'Asia' },
    'AW': { name: 'Aruba', flag: '🇦🇼', continent: 'América del Norte' },
    'AU': { name: 'Australia', flag: '🇦🇺', continent: 'Oceanía' },
    'AT': { name: 'Austria', flag: '🇦🇹', continent: 'Europa' },
    'AZ': { name: 'Azerbaiyán', flag: '🇦🇿', continent: 'Asia' },
    'BS': { name: 'Bahamas', flag: '🇧🇸', continent: 'América del Norte' },
    'BH': { name: 'Bahréin', flag: '🇧🇭', continent: 'Asia' },
    'BD': { name: 'Bangladés', flag: '🇧🇩', continent: 'Asia' },
    'BB': { name: 'Barbados', flag: '🇧🇧', continent: 'América del Norte' },
    'BE': { name: 'Bélgica', flag: '🇧🇪', continent: 'Europa' },
    'BZ': { name: 'Belize', flag: '🇧🇿', continent: 'América del Norte' },
    'BM': { name: 'Bermuda', flag: '🇧🇲', continent: 'América del Norte' },
    'BY': { name: 'Bielorrusia', flag: '🇧🇾', continent: 'Europa' },
    'MM': { name: 'Birmania', flag: '🇲🇲', continent: 'Asia' },
    'BO': { name: 'Bolivia', flag: '🇧🇴', continent: 'América del Sur' },
    'BA': { name: 'Bosnia y Herzegovina', flag: '🇧🇦', continent: 'Europa' },
    'BW': { name: 'Botswana', flag: '🇧🇼', continent: 'África' },
    'BR': { name: 'Brasil', flag: '🇧🇷', continent: 'América del Sur' },
    'BN': { name: 'Brunei', flag: '🇧🇳', continent: 'Asia' },
    'BG': { name: 'Bulgaria', flag: '🇧🇬', continent: 'Europa' },
    'BI': { name: 'Burundi', flag: '🇧🇮', continent: 'África' },
    'BT': { name: 'Bután', flag: '🇧🇹', continent: 'Asia' },
    'CV': { name: 'Cabo Verde', flag: '🇨🇻', continent: 'África' },
    'KH': { name: 'Camboya', flag: '🇰🇭', continent: 'Asia' },
    'CM': { name: 'Camerún', flag: '🇨🇲', continent: 'África' },
    'CA': { name: 'Canadá', flag: '🇨🇦', continent: 'América del Norte' },
    'TD': { name: 'Chad', flag: '🇹🇩', continent: 'África' },
    'CS': { name: 'Checoslovaquia', flag: '🏴', continent: 'Europa (Histórico)' },
    'CL': { name: 'Chile', flag: '🇨🇱', continent: 'América del Sur' },
    'CN': { name: 'China República Popular', flag: '🇨🇳', continent: 'Asia' },
    'CY': { name: 'Chipre', flag: '🇨🇾', continent: 'Europa' },
    'CO': { name: 'Colombia', flag: '🇨🇴', continent: 'América del Sur' },
    'KM': { name: 'Comoras', flag: '🇰🇲', continent: 'África' },
    'CG': { name: 'Congo República Brazzaville', flag: '🇨🇬', continent: 'África' },
    'CD': { name: 'Congo República Democrática', flag: '🇨🇩', continent: 'África' },
    'KP': { name: 'Corea del Norte', flag: '🇰🇵', continent: 'Asia' },
    'KR': { name: 'Corea del Sur', flag: '🇰🇷', continent: 'Asia' },
    'CI': { name: 'Costa de Marfil', flag: '🇨🇮', continent: 'África' },
    'CR': { name: 'Costa Rica', flag: '🇨🇷', continent: 'América del Norte' },
    'HR': { name: 'Croacia', flag: '🇭🇷', continent: 'Europa' },
    'CU': { name: 'Cuba', flag: '🇨🇺', continent: 'América del Norte' },
    'CW': { name: 'Curacao', flag: '🇨🇼', continent: 'América del Norte' },
    'DK': { name: 'Dinamarca', flag: '🇩🇰', continent: 'Europa' },
    'DM': { name: 'Dominica', flag: '🇩🇲', continent: 'América del Norte' },
    'EC': { name: 'Ecuador', flag: '🇪🇨', continent: 'América del Sur' },
    'EG': { name: 'Egipto', flag: '🇪🇬', continent: 'África' },
    'SV': { name: 'El Salvador', flag: '🇸🇻', continent: 'América del Norte' },
    'AE': { name: 'Emiratos Árabes Unidos', flag: '🇦🇪', continent: 'Asia' },
    'ER': { name: 'Eritrea', flag: '🇪🇷', continent: 'África' },
    'SK': { name: 'Eslovaquia', flag: '🇸🇰', continent: 'Europa' },
    'SI': { name: 'Eslovenia', flag: '🇸🇮', continent: 'Europa' },
    'ES': { name: 'España', flag: '🇪🇸', continent: 'Europa' },
    'US': { name: 'Estados Unidos de América', flag: '🇺🇸', continent: 'América del Norte' },
    'EE': { name: 'Estonia', flag: '🇪🇪', continent: 'Europa' },
    'SZ': { name: 'Eswatini', flag: '🇸🇿', continent: 'África' },
    'ET': { name: 'Etiopía', flag: '🇪🇹', continent: 'África' },
    'PH': { name: 'Filipinas', flag: '🇵🇭', continent: 'Asia' },
    'FI': { name: 'Finlandia', flag: '🇫🇮', continent: 'Europa' },
    'FJ': { name: 'Fiyi', flag: '🇫🇯', continent: 'Oceanía' },
    'FR': { name: 'Francia', flag: '🇫🇷', continent: 'Europa' },
    'GA': { name: 'Gabón', flag: '🇬🇦', continent: 'África' },
    'GM': { name: 'Gambia', flag: '🇬🇲', continent: 'África' },
    'GE': { name: 'Georgia', flag: '🇬🇪', continent: 'Asia' },
    'GH': { name: 'Ghana', flag: '🇬🇭', continent: 'África' },
    'GI': { name: 'Gibraltar', flag: '🇬🇮', continent: 'Europa' },
    'GD': { name: 'Granada', flag: '🇬🇩', continent: 'América del Norte' },
    'GR': { name: 'Grecia', flag: '🇬🇷', continent: 'Europa' },
    'GL': { name: 'Groenlandia', flag: '🇬🇱', continent: 'América del Norte' },
    'GP': { name: 'Guadalupe', flag: '🇬🇵', continent: 'América del Norte' },
    'GT': { name: 'Guatemala', flag: '🇬🇹', continent: 'América del Norte' },
    'GG': { name: 'Guernsey', flag: '🇬🇬', continent: 'Europa' },
    'GN': { name: 'Guinea', flag: '🇬🇳', continent: 'África' },
    'GQ': { name: 'Guinea Ecuatorial', flag: '🇬🇶', continent: 'África' },
    'GW': { name: 'Guinea-Bissau', flag: '🇬🇼', continent: 'África' },
    'GY': { name: 'Guyana', flag: '🇬🇾', continent: 'América del Sur' },
    'HT': { name: 'Haití', flag: '🇭🇹', continent: 'América del Norte' },
    'HN': { name: 'Honduras', flag: '🇭🇳', continent: 'América del Norte' },
    'HK': { name: 'Hong Kong', flag: '🇭🇰', continent: 'Asia' },
    'HU': { name: 'Hungría', flag: '🇭🇺', continent: 'Europa' },
    'IN': { name: 'India', flag: '🇮🇳', continent: 'Asia' },
    'ID': { name: 'Indonesia', flag: '🇮🇩', continent: 'Asia' },
    'IR': { name: 'Irán', flag: '🇮🇷', continent: 'Asia' },
    'IQ': { name: 'Irak', flag: '🇮🇶', continent: 'Asia' },
    'IE': { name: 'Irlanda', flag: '🇮🇪', continent: 'Europa' },
    'IM': { name: 'Isla de Man', flag: '🇮🇲', continent: 'Europa' },
    'IS': { name: 'Islandia', flag: '🇮🇸', continent: 'Europa' },
    'KY': { name: 'Islas Caimán', flag: '🇰🇾', continent: 'América del Norte' },
    'CK': { name: 'Islas Cook', flag: '🇨🇰', continent: 'Oceanía' },
    'FO': { name: 'Islas Feroe', flag: '🇫🇴', continent: 'Europa' },
    'FK': { name: 'Islas Malvinas', flag: '🇫🇰', continent: 'América del Sur' },
    'SB': { name: 'Islas Salomón', flag: '🇸🇧', continent: 'Oceanía' },
    'TC': { name: 'Islas Turcas y Caicos', flag: '🇹🇨', continent: 'América del Norte' },
    'IL': { name: 'Israel', flag: '🇮🇱', continent: 'Asia' },
    'IT': { name: 'Italia', flag: '🇮🇹', continent: 'Europa' },
    'JM': { name: 'Jamaica', flag: '🇯🇲', continent: 'América del Norte' },
    'JP': { name: 'Japón', flag: '🇯🇵', continent: 'Asia' },
    'JE': { name: 'Jersey', flag: '🇯🇪', continent: 'Europa' },
    'JO': { name: 'Jordania', flag: '🇯🇴', continent: 'Asia' },
    'KZ': { name: 'Kazajstán', flag: '🇰🇿', continent: 'Asia' },
    'KE': { name: 'Kenia', flag: '🇰🇪', continent: 'África' },
    'KG': { name: 'Kirguistán', flag: '🇰🇬', continent: 'Asia' },
    'XK': { name: 'Kosovo', flag: '🇽🇰', continent: 'Europa' },
    'KW': { name: 'Kuwait', flag: '🇰🇼', continent: 'Asia' },
    'LA': { name: 'Laos', flag: '🇱🇦', continent: 'Asia' },
    'LS': { name: 'Lesotho', flag: '🇱🇸', continent: 'África' },
    'LV': { name: 'Letonia', flag: '🇱🇻', continent: 'Europa' },
    'LB': { name: 'Líbano', flag: '🇱🇧', continent: 'Asia' },
    'LR': { name: 'Liberia', flag: '🇱🇷', continent: 'África' },
    'LY': { name: 'Libia', flag: '🇱🇾', continent: 'África' },
    'LI': { name: 'Liechtenstein', flag: '🇱🇮', continent: 'Europa' },
    'LT': { name: 'Lituania', flag: '🇱🇹', continent: 'Europa' },
    'LU': { name: 'Luxemburgo', flag: '🇱🇺', continent: 'Europa' },
    'MO': { name: 'Macao', flag: '🇲🇴', continent: 'Asia' },
    'MK': { name: 'Macedonia del Norte', flag: '🇲🇰', continent: 'Europa' },
    'MG': { name: 'Madagascar', flag: '🇲🇬', continent: 'África' },
    'MY': { name: 'Malasia', flag: '🇲🇾', continent: 'Asia' },
    'MW': { name: 'Malawi', flag: '🇲🇼', continent: 'África' },
    'MV': { name: 'Maldivas', flag: '🇲🇻', continent: 'Asia' },
    'ML': { name: 'Malí', flag: '🇲🇱', continent: 'África' },
    'MT': { name: 'Malta', flag: '🇲🇹', continent: 'Europa' },
    'MA': { name: 'Marruecos', flag: '🇲🇦', continent: 'África' },
    'MQ': { name: 'Martinica', flag: '🇲🇶', continent: 'América del Norte' },
    'MU': { name: 'Mauricio', flag: '🇲🇺', continent: 'África' },
    'MR': { name: 'Mauritania', flag: '🇲🇷', continent: 'África' },
    'MX': { name: 'México', flag: '🇲🇽', continent: 'América del Norte' },
    'MD': { name: 'Moldavia', flag: '🇲🇩', continent: 'Europa' },
    'MC': { name: 'Mónaco', flag: '🇲🇨', continent: 'Europa' },
    'MN': { name: 'Mongolia', flag: '🇲🇳', continent: 'Asia' },
    'ME': { name: 'Montenegro', flag: '🇲🇪', continent: 'Europa' },
    'MZ': { name: 'Mozambique', flag: '🇲🇿', continent: 'África' },
    'NA': { name: 'Namibia', flag: '🇳🇦', continent: 'África' },
    'NP': { name: 'Nepal', flag: '🇳🇵', continent: 'Asia' },
    'NI': { name: 'Nicaragua', flag: '🇳🇮', continent: 'América del Norte' },
    'NG': { name: 'Nigeria', flag: '🇳🇬', continent: 'África' },
    'NO': { name: 'Noruega', flag: '🇳🇴', continent: 'Europa' },
    'NC': { name: 'Nueva Caledonia', flag: '🇳🇨', continent: 'Oceanía' },
    'NZ': { name: 'Nueva Zelanda', flag: '🇳🇿', continent: 'Oceanía' },
    'NL': { name: 'Países Bajos', flag: '🇳🇱', continent: 'Europa' },
    'PK': { name: 'Pakistán', flag: '🇵🇰', continent: 'Asia' },
    'PA': { name: 'Panamá', flag: '🇵🇦', continent: 'América del Norte' },
    'PG': { name: 'Papúa Nueva Guinea', flag: '🇵🇬', continent: 'Oceanía' },
    'PY': { name: 'Paraguay', flag: '🇵🇾', continent: 'América del Sur' },
    'PE': { name: 'Perú', flag: '🇵🇪', continent: 'América del Sur' },
    'PL': { name: 'Polonia', flag: '🇵🇱', continent: 'Europa' },
    'PT': { name: 'Portugal', flag: '🇵🇹', continent: 'Europa' },
    'PR': { name: 'Puerto Rico', flag: '🇵🇷', continent: 'América del Norte' },
    'QA': { name: 'Qatar', flag: '🇶🇦', continent: 'Asia' },
    'GB': { name: 'Reino Unido', flag: '🇬🇧', continent: 'Europa' },
    'CF': { name: 'República Centroafricana', flag: '🇨🇫', continent: 'África' },
    'CZ': { name: 'República Checa', flag: '🇨🇿', continent: 'Europa' },
    'DO': { name: 'República Dominicana', flag: '🇩🇴', continent: 'América del Norte' },
    'RE': { name: 'Reunión', flag: '🇷🇪', continent: 'África' },
    'RW': { name: 'Ruanda', flag: '🇷🇼', continent: 'África' },
    'RO': { name: 'Rumanía', flag: '🇷🇴', continent: 'Europa' },
    'RU': { name: 'Rusia', flag: '🇷🇺', continent: 'Europa' },
    'WS': { name: 'Samoa', flag: '🇼🇸', continent: 'Oceanía' },
    'SM': { name: 'San Marino', flag: '🇸🇲', continent: 'Europa' },
    'PM': { name: 'San Pedro y Miquelón', flag: '🇵🇲', continent: 'América del Norte' },
    'VC': { name: 'San Vicente y las Granadinas', flag: '🇻🇨', continent: 'América del Norte' },
    'SH': { name: 'Santa Helena', flag: '🇸🇭', continent: 'África' },
    'LC': { name: 'Santa Lucía', flag: '🇱🇨', continent: 'América del Norte' },
    'ST': { name: 'Santo Tomé y Príncipe', flag: '🇸🇹', continent: 'África' },
    'SN': { name: 'Senegal', flag: '🇸🇳', continent: 'África' },
    'RS': { name: 'Serbia', flag: '🇷🇸', continent: 'Europa' },
    'SC': { name: 'Seychelles', flag: '🇸🇨', continent: 'África' },
    'SL': { name: 'Sierra Leona', flag: '🇸🇱', continent: 'África' },
    'SG': { name: 'Singapur', flag: '🇸🇬', continent: 'Asia' },
    'SY': { name: 'Siria', flag: '🇸🇾', continent: 'Asia' },
    'SO': { name: 'Somalia', flag: '🇸🇴', continent: 'África' },
    'LK': { name: 'Sri Lanka', flag: '🇱🇰', continent: 'Asia' },
    'ZA': { name: 'Sudáfrica', flag: '🇿🇦', continent: 'África' },
    'SD': { name: 'Sudán', flag: '🇸🇩', continent: 'África' },
    'SS': { name: 'Sudán del Sur', flag: '🇸🇸', continent: 'África' },
    'SE': { name: 'Suecia', flag: '🇸🇪', continent: 'Europa' },
    'CH': { name: 'Suiza', flag: '🇨🇭', continent: 'Europa' },
    'SR': { name: 'Surinam', flag: '🇸🇷', continent: 'América del Sur' },
    'TH': { name: 'Tailandia', flag: '🇹🇭', continent: 'Asia' },
    'TW': { name: 'Taiwán', flag: '🇹🇼', continent: 'Asia' },
    'TZ': { name: 'Tanzania', flag: '🇹🇿', continent: 'África' },
    'TJ': { name: 'Tayikistán', flag: '🇹🇯', continent: 'Asia' },
    'TL': { name: 'Timor', flag: '🇹🇱', continent: 'Asia' },
    'TO': { name: 'Tonga', flag: '🇹🇴', continent: 'Oceanía' },
    'TT': { name: 'Trinidad y Tobago', flag: '🇹🇹', continent: 'América del Norte' },
    'TN': { name: 'Túnez', flag: '🇹🇳', continent: 'África' },
    'TR': { name: 'Turquía', flag: '🇹🇷', continent: 'Asia' },
    'TM': { name: 'Turkmenistán', flag: '🇹🇲', continent: 'Asia' },
    'UA': { name: 'Ucrania', flag: '🇺🇦', continent: 'Europa' },
    'UG': { name: 'Uganda', flag: '🇺🇬', continent: 'África' },
    'UY': { name: 'Uruguay', flag: '🇺🇾', continent: 'América del Sur' },
    'UZ': { name: 'Uzbekistán', flag: '🇺🇿', continent: 'Asia' },
    'VU': { name: 'Vanuatu', flag: '🇻🇺', continent: 'Oceanía' },
    'VE': { name: 'Venezuela', flag: '🇻🇪', continent: 'América del Sur' },
    'VN': { name: 'Vietnam', flag: '🇻🇳', continent: 'Asia' },
    'YE': { name: 'Yemen', flag: '🇾🇪', continent: 'Asia' },
    'DJ': { name: 'Yibuti', flag: '🇩🇯', continent: 'África' },
    'YU': { name: 'Yugoslavia', flag: '🏴', continent: 'Europa (Histórico)' },
    'ZM': { name: 'Zambia', flag: '🇿🇲', continent: 'África' },
    'ZW': { name: 'Zimbabue', flag: '🇿🇼', continent: 'África' },
    'EU': { name: 'Unión Europea', flag: '🇪🇺', continent: 'Europa' },
    
    // Países y territorios históricos adicionales
    'USSR': { name: 'Unión Soviética', flag: '🏴', continent: 'Europa/Asia (Histórico)' },
    'PRU': { name: 'Prusia', flag: '🏴', continent: 'Europa (Histórico)' },
    'AH': { name: 'Imperio Austro-Húngaro', flag: '🏴', continent: 'Europa (Histórico)' },
    'ROM': { name: 'Imperio Romano', flag: '🏛️', continent: 'Europa (Histórico)' },
    'BYZ': { name: 'Imperio Bizantino', flag: '⛪', continent: 'Europa (Histórico)' },
    'CSA': { name: 'Estados Confederados de América', flag: '🏴', continent: 'América del Norte (Histórico)' },
    'TX': { name: 'República de Texas', flag: '🏴', continent: 'América del Norte (Histórico)' },
    'HI': { name: 'Hawái', flag: '🏴', continent: 'Oceanía (Histórico)' },
    'CEY': { name: 'Ceilán', flag: '🏴', continent: 'Asia (Histórico)' },
    'ZAR': { name: 'Zaire', flag: '🏴', continent: 'África (Histórico)' },
    'RHO': { name: 'Rhodesia', flag: '🏴', continent: 'África (Histórico)' },
    'ZAN': { name: 'Zanzíbar', flag: '🏴', continent: 'África (Histórico)' },
    'DAN': { name: 'Danzig, Ciudad Libre', flag: '🏴', continent: 'Europa (Histórico)' },
    'FIU': { name: 'Fiume', flag: '🏴', continent: 'Europa (Histórico)' },
    'SAR': { name: 'Sarre', flag: '🏴', continent: 'Europa (Histórico)' },
    'MEM': { name: 'Memel Territorio', flag: '🏴', continent: 'Europa (Histórico)' },
    'BOH': { name: 'Bohemia y Moravia', flag: '🏴', continent: 'Europa (Histórico)' },
    'BIA': { name: 'Biafra', flag: '🏴', continent: 'África (Histórico)' },
    'KAT': { name: 'Katanga', flag: '🏴', continent: 'África (Histórico)' },
    'TAN': { name: 'Tánger', flag: '🏴', continent: 'África (Histórico)' },
    'TIB': { name: 'Tíbet', flag: '🏴', continent: 'Asia (Histórico)' },
    'TUV': { name: 'Tannu Tuva', flag: '🏴', continent: 'Asia (Histórico)' },
    'TAT': { name: 'Tatarstán', flag: '🏴', continent: 'Europa' },
    'TRA': { name: 'Transnistria', flag: '🏴', continent: 'Europa' }
};