services:
  - type: web
    name: coin-collection-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python backend.py
    envVars:
      - key: PORT
        value: 10000